### ISSUE TITLE
static linking to dlib

### ISSUE THREAD

**Issue by frpunzalan** [Kagami/go-face#3] opened 2018-08-17 03:12 UTC
Hi,
I was trying to check how go-face links to dlib and it seems that it links to a dynamic library. This might be an issue if I want to transfer a binary to another machine (or a docker container) since both dlib and mkl libraries (plus dependencies) needs around ~1 GB of disk space.

Is it possible to link go-face to a statically link to dlib so that we can compile a stand-alone binary?

**Comment by Kagami** [comment] 2018-08-17 06:42
Should be possible in case of dlib, not sure about mkl. Might try with e.g. openblas instead.

**Comment by Kagami** [comment] 2019-01-04 14:55
Closing because it's out of scope of go-face.
Should be possible with something like `CGO_LDFLAGS="-static"` but don't have time to test this, because you also need static (`.a`) version of all libraries that dlib depends on.

**Closed by Kagami** 2019-01-04 14:55 UTC

**Comment by tpoxa** [comment] 2020-03-23 15:41
@frpunzalan  I managed to build go-face application statically in docker.
Its based on Ubuntu 19.04 base image.

Dockerfile.ubuntu19.04
```
FROM ubuntu:19.04 as base
RUn apt-get update
RUN apt-get update && apt-get install pkg-config libdlib-dev libopenblas-dev libgfortran-8-dev libjpeg-turbo8-dev -y
ADD dlib-1.pc /usr/local/lib/pkgconfig/
RUN pkg-config --cflags  -- dlib-1
```

dlib-1.pc
```
libdir=/usr/lib/x86_64-linux-gnu
includedir=/usr/include

Name: dlib
Description: Numerical and networking C++ library
Version: 19.10.0
Libs: -L${libdir} -ldlib -lblas -llapack -lgfortran -lquadmath
Cflags: -I${includedir}
Requires:
```
These two files give you basic environment with dev dependencies ready for static build. I named this image dlibubuntu

Next goes golang 1.13.8 base image with go-face library built in the $GOPATH
Because go-face installation takes much time I decided to make it as separate docker image.

```
FROM dlibubuntu as builder
RUN apt-get install wget git gcc -y

RUN wget https://dl.google.com/go/go1.13.8.linux-amd64.tar.gz
RUN tar -xf go1.13.8.linux-amd64.tar.gz
RUN mv go /usr/local

ENV GOROOT /usr/local/go
ENV GOPATH /go
ENV PATH $GOPATH/bin:$GOROOT/bin:$PATH
RUN mkdir $GOPATH
RUN go get -v github.com/Kagami/go-face 
```
Last one. Your golang application which is using go-face. Basically app the same as example one. I provide here only its Dockerfile. 

```
FROM goface:latest as builder
WORKDIR /go/src/service
ADD . .
RUN CGO_LDFLAGS="-static" CGO_ENABLED=1 GOOS=linux go build

FROM alpine
WORKDIR /root
COPY --from=builder /go/src/service /root
```

Run
```
docker run -it facerecognize:latest /root/service
Nayoung
```

One restriction here user app should be in GOPATH to re-use go-face package.
I hope this will help someone.

**Comment by Jumanjii** [comment] 2020-09-06 23:01
Hello @tpoxa , 
Thanks for your research with Docker. 
Reproducing what you've done and fixing little issues I reached to have the example program running in the container (using `go run`).

Still, I'm fighting with an issue when trying to build the binary
using `
CGO_LDFLAGS="-static" CGO_ENABLED=1 GOOS=linux go build`

Does the following error is bringing some bells to you?

```
(.text+0x9cd): undefined reference to `_gfortran_concat_string'
```

**Comment by AgentNemo** [comment] 2021-01-29 22:31
`(.text+0x781): more undefined references to `_gfortran_concat_string' follow
collect2`

i have the same error

**Comment by vearutop** [comment] 2024-02-01 13:55
I've managed to build static binary with dlib with such a `Dockerfile` and reduced ldflags in `face.go`.
```go
// #cgo LDFLAGS: -ldlib
import "C"
```
https://github.com/vearutop/faces/blob/v0.1.4/vendor/github.com/Kagami/go-face/face_static.go


```Dockerfile
FROM ubuntu:22.04 as builder

RUN apt-get update
RUN apt-get install -y build-essential cmake curl
RUN curl -sLO https://go.dev/dl/go1.21.6.linux-amd64.tar.gz && tar -C /usr/local -xzf go1.21.6.linux-amd64.tar.gz && rm -rf go1.21.6.linux-amd64.tar.gz
RUN mkdir /dlib && cd /dlib && curl -sLO http://dlib.net/files/dlib-19.24.tar.bz2 && tar xf dlib-19.24.tar.bz2
RUN cd /dlib/dlib-19.24 && mkdir build && cd build && cmake .. && cmake --build . --config Release && make install && rm -rf /dlib

# Missing header file.
RUN cp /usr/local/include/dlib/external/libjpeg/*.h /usr/include/

# Building app.
WORKDIR /app
ADD . .
RUN CGO_LDFLAGS="-static" /usr/local/go/bin/go build -tags static .

# Exporting minimal docker image with pre-built binary.
FROM alpine
WORKDIR /root
CMD ["/bin/faces", "-listen", "0.0.0.0:80"]
COPY --from=builder /app/faces /bin/faces
```

More info in a [blog post](https://dev.to/vearutop/building-a-portable-face-recognition-application-with-go-and-dlib-12p1).
