### ISSUE TITLE
GitHub.com/Kagami/go-face

### ISSUE THREAD

**Issue by shivesh86** [Kagami/go-face#49] opened 2020-05-06 18:10 UTC
Facing below issue:

# github.com/Kagami/go-face
../../pkg/mod/github.com/!kagami/go-face@v0.0.0-20180922080525-863b26a6405e/face.go:25:7: identifier "_Ctype_struct_facerec" may conflict with identifiers generated by cgo

Go Version : 1.14.2
Mac OS : 10.15.4

**Comment by Kagami** [comment] 2020-05-11 10:03
Duplicate of #47

**Closed by Kagami** 2020-05-11 10:03 UTC
