### ISSUE TITLE
identifier "_Ctype_struct_facerec" may conflict with identifiers generated by cgo

### ISSUE THREAD

**Issue by nathany** [Kagami/go-face#21] opened 2019-02-26 17:21 UTC
In Go 1.12 there is the following error:

```
❯ go build
# github.com/Kagami/go-face
./face.go:25:7: identifier "_Ctype_struct_facerec" may conflict with identifiers generated by cgo
```

macOS 10.14.3, dlib 19.16 via Homebrew. It compiles without error in Go 1.11 after running the `sed` command in the README.

**Comment by Kagami** [comment] 2019-02-26 21:26
Duplicate of #22

**Closed by Kagami** 2019-02-26 21:26 UTC

**Comment by nathany** [comment] 2019-02-26 21:28
Whoops, sorry for the dup.
