### ISSUE TITLE
only Recognizer jpeg image,can't support png 

### ISSUE THREAD

**Issue by foreachsky** [Kagami/go-face#48] opened 2020-04-17 09:56 UTC
hi ,i user opencv to detect the face regoin,then use go-face to recognizer ,i put []byte to call Recognize() function,but it's error:
jpeg_mem_loader: decode error: Not a JPEG file: starts with 0x75 0x93

**Comment by tpoxa** [comment] 2020-04-17 12:36
So yes, only JPEG format supported currently.

**Comment by Kagami** [comment] 2020-05-11 10:02
Duplicate of #45

**Closed by Kagami** 2020-05-11 10:02 UTC
